### ISSUE TITLE
Not all Filess Included

### ISSUE THREAD

**Issue by MoinSchmoin** [pytr-org/pytr#41]

**Comment by PiLoT650** [comment]
Not a solution but a workaround - seems related to #36 
if you play with the days - for example start with 60 and then 90 - most of the time
i'll get all documents on second / third try.

**Comment by marzzzello** [comment]
Can you give more information? Which files are not included?

**Comment by Akaame** [comment]
If you are talking about the files for the new transactions (like within the last two days), it is possible that you have not gotten a machine created Abrechnung yet and might have to wait for the Trade Republic machines actually tackle that. This happens especially with savings plans because most of the executions coincide.

If that is not the case you were mentioning please provide an example of what you expected and what actually happened

**Comment by Katzmann1983** [comment]
Closse since outdated
